export const ROLES = {
  comprador: {
    id: 'comprador',
    label: 'Comprador',
    canCreate: true,
    canEdit: true,
    canApprove: false,
    canDrag: true,
    canAccessSettings: false,
    color: 'bg-sky-100 text-sky-700',
    badgeColor: '#0EA5E9',
  },
  coordenador: {
    id: 'coordenador',
    label: 'Coordenador',
    canCreate: false,
    canEdit: false,
    canApprove: true,
    approveColumns: ['coordenacao'],
    canDrag: false,
    canAccessSettings: false,
    color: 'bg-blue-100 text-blue-700',
    badgeColor: '#3B82F6',
  },
  gestor: {
    id: 'gestor',
    label: 'Gestor',
    canCreate: false,
    canEdit: false,
    canApprove: true,
    approveColumns: ['gestor'],
    canDrag: false,
    canAccessSettings: false,
    color: 'bg-violet-100 text-violet-700',
    badgeColor: '#8B5CF6',
  },
  diretor: {
    id: 'diretor',
    label: 'Diretor',
    canCreate: false,
    canEdit: false,
    canApprove: true,
    approveColumns: ['diretor'],
    canDrag: false,
    canAccessSettings: false,
    color: 'bg-red-100 text-red-700',
    badgeColor: '#EF4444',
  },
  admin: {
    id: 'admin',
    label: 'Admin',
    canCreate: true,
    canEdit: true,
    canApprove: true,
    approveColumns: ['coordenacao', 'gestor', 'diretor'],
    canDrag: true,
    canAccessSettings: true,
    color: 'bg-orange-100 text-orange-700',
    badgeColor: '#F97316',
  },
}

export const DEMO_USERS = [
  { id:'u1', name:'Ana Lima',    email:'ana.lima@stone.com.br',    role:'comprador',   avatar:'AL', passwordHash:null, mustChangePassword:true  },
  { id:'u2', name:'Bruno Costa', email:'bruno.costa@stone.com.br', role:'coordenador', avatar:'BC', passwordHash:null, mustChangePassword:true  },
  { id:'u3', name:'Carla Melo',  email:'carla.melo@stone.com.br',  role:'gestor',      avatar:'CM', passwordHash:null, mustChangePassword:true  },
  { id:'u4', name:'Diego Faria', email:'diego.faria@stone.com.br', role:'diretor',     avatar:'DF', passwordHash:null, mustChangePassword:true  },
  { id:'u5', name:'Paulo Vidal', email:'paulo.vidal@stone.com.br', role:'admin',       avatar:'PV', passwordHash:null, mustChangePassword:false },
]
